version: '3.8'

services:
  tradingbot:
    build: .
    container_name: tradingbot
    ports:
      - "8002:8001"
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - pytrader_signalcraft_network

networks:
  pytrader_signalcraft_network:
    external: true